CREATE TABLE CUSTOMERS(
    CUSTOMER_ID NUMBER,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUSTOMER_ID),
    COMPANY_NAME NVARCHAR2(50),
    CONTACT_NAME NVARCHAR2(50),
    CONTACT_TITLE NVARCHAR2(50),
    ADDRESS NVARCHAR2(50),
    CITY NVARCHAR2(50),
    REGION NVARCHAR2(50),
    POSTAL_CODE NVARCHAR2(50),
    COUNTRY NVARCHAR2(50),
    PHONE NUMBER,
    FAX NVARCHAR2(50)
);