CREATE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER,
    CONSTRAINT SUPLIER_PK PRIMARY KEY(SUPPLIER_ID),
    COMPANY_NAME NVARCHAR2(50),
    CONTACT_NAME NVARCHAR2(50),
    CONTACT_TITLE NVARCHAR2(100),
    ADDRESS NVARCHAR2(50),
    CITY NVARCHAR2(50),
    REGION NVARCHAR2(50),
    POSTAL_CODE NVARCHAR2(50),
    COUNTRY NVARCHAR2(50),
    PHONE NUMBER,
    FAX NVARCHAR2(50),
    HOME_PAGE NVARCHAR2(50)
);