SELECT DIRECTOR, COUNT(ID) FROM MOVIE
GROUP BY(DIRECTOR);

SELECT DIRECTOR, SUM(DOMESTIC_SALES), SUM(INTERNATIONAL_SALES) FROM MOVIE JOIN MOVIE_STAT ON MOVIE.ID = MOVIE_STAT.MOVIE_ID
GROUP BY DIRECTOR;