CREATE TABLE FORUM_POSTS(
    ID NUMBER,
    CONSTRAINT FORUM_POST_PK PRIMARY KEY(ID),
    ID_SUBCATEGORY NUMBER,
    CONSTRAINT FORUM_SUBCATEGORY_FK FOREIGN KEY(ID_SUBCATEGORY) REFERENCES FORUM_SUBCATEGORIES(ID),
    ID_USER NUMBER,
    CONSTRAINT USER_FK FOREIGN KEY(ID_USER) REFERENCES USERS(ID),
    PARENT_POST NUMBER,
    CONSTRAINT PARENT_POST_FK FOREIGN KEY(PARENT_POST) REFERENCES FORUM_POSTS(ID),
    TITLE NVARCHAR2(90),
    CONTENT CLOB,
    IS_POLL NUMBER(1) DEFAULT 0,
    POST_DATE TIMESTAMP,
    IP NVARCHAR2(20)
);