CREATE TABLE ORDERS1(
    ID NUMBER CHECK (ID < 1000),
    CONSTRAINT ORDER_ID PRIMARY KEY (ID),
    USER_ID NUMBER UNIQUE NOT NULL,
    ROOM_ID NUMBER UNIQUE NOT NULL,
    DATE_FROM TIMESTAMP,
    DATE_TO TIMESTAMP,
    MONEY_PAID NUMBER(*, 2)
);