CREATE TABLE HOTELS (
    ID NUMBER,
    CONSTRAINT HOTEL_ID PRIMARY KEY (ID),
    COUNTRY NVARCHAR2(50) DEFAULT 'N/A',
    CONSTRAINT CHECK_HC CHECK (COUNTRY != 'ROMANIA' AND COUNTRY != 'BELGIUM' AND COUNTRY != 'CHINA' AND COUNTRY != 'UKRAINE'),
    CITY NVARCHAR2(50) NOT NULL,
    STREET NVARCHAR2(50)
);