ALTER TABLE EMPLOYEES
DROP (PHOTO, NOTES, REPORTS_TO);

ALTER TABLE PRODUCTS
DROP CONSTRAINT SUPPLIER_FK;
ALTER TABLE SUPPLIERS
DROP CONSTRAINT SUPPLIER_PK;
ALTER TABLE SUPPLIERS
ADD CONSTRAINT PHONE_PK PRIMARY KEY (PHONE);

ALTER TABLE CUSTOMERS
ADD IS_ACTIVE NUMBER DEFAULT 0 CHECK (IS_ACTIVE BETWEEN 0 AND 1) NOT NULL;

ALTER TABLE CATEGORIES
MODIFY PICTURE NVARCHAR2(100);