SELECT CUSTOMER.CUSTNAME, CUSTOMER.CITY, SALESMAN.NAME, SALESMAN.CITY FROM CUSTOMER
JOIN SALESMAN ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE DEAL.AMOUNT > 10000;

SELECT CUSTOMER.CUSTNAME FROM CUSTOMER
JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
WHERE DEAL.DEAL_DATE BETWEEN TO_DATE('2017/01/01 00:00:00', 'yyyy/mm/dd hh24:mi:ss')
AND TO_DATE('2018/12/31 00:00:00', 'yyyy/mm/dd hh24:mi:ss');

SELECT SALESMAN.NAME, SUM(DEAL.AMOUNT) FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
WHERE DEAL.DEAL_DATE BETWEEN TO_DATE('2017/08/01 00:00:00', 'yyyy/mm/dd hh24:mi:ss') AND TO_DATE('2017/08/31 00:00:00', 'yyyy/mm/dd hh24:mi:ss')
GROUP BY SALESMAN.NAME;